### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by grayskripko** [ugorsahin/ChatGPT_Automation#12]
Sorry for disturbing you for the second time about the similar question.
It just took me 2 days to prepare my system to use your package. Though it still not ready.
It seems the installation of undetected-chromedriver could be painful. It requires 2 files and if you haven't worked with it earlier you should somehow guess their names, versions and compability of versions. undetected-chromedriver doesn't have a good installation manual. 

My current one 
```
sudo apt-get install libc-dev

wget https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_linux64.zip
unzip chromedriver_linux64.zip
sudo mv chromedriver /usr/bin/
sudo chmod +x /usr/bin/chromedriver

wget dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_113.0.5672.92-1_amd64.deb
sudo dpkg -i google-chrome-stable_113.0.5672.92-1_amd64.deb
```
Though I'm not still sure it will work with you package. At the moment it worked for running undetected-chromedriver but I used ChromeOptions and your ChatGPT_Client doesn't allow me to do the same. I'm confused with system environments and PATH. Which of chrome files I should to specify and where.

So I ask you to consider adding my commands in case they are right and describe what environment variables and PATH additions your package expects.

**Comment by ugorsahin** [comment]
Perhaps the issue is present due to version information is hardcoded in the initialization. Try updating the version argument 112 to 113.

```
        self.browser = uc.Chrome(
            # driver_executable_path='/usr/bin/google-chrome',
            options=options,
            headless=headless,
            version_main=112
        )
```

In the meantime, I will work on a solution to solve this issue.

**Comment by grayskripko** [comment]
actually, I don't understand how to use it. I mean if I create a ChatGPT_client object in order to assign a browser later, I face with the line 
```
self.browser.get('https://chat.openai.com/auth/login?next=/chat')
```
that will throw an error.

At the moment, I'll try to rewrite the whole constuctor

**Comment by ugorsahin** [comment]
Do you still have any problems with this? I updated the repo with 6cde457cf3dce8b3e654e176240667dbb506a90f, perhaps this can help you.

**Comment by grayskripko** [comment]
I used a workaround. Based on your constructor I created my own and added everything I needed
