### ISSUE TITLE
No Such Element for reset_xq

### ISSUE THREAD

**Issue by MovieHolic-Plex** [ugorsahin/ChatGPT_Automation#26]
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[text()="New chat"]"}
  (Session info: chrome=113.0.5672.127)

so it should be replaced by     
reset_xq    = '//a[span[text()="New chat"]]'

**Comment by ugorsahin** [comment]
Hey, thanks for the correction!

Would you like to send a PR? I would be happy to confirm it.

**Comment by ugorsahin** [comment]
It is now fixed with commit [203a0a8](https://github.com/ugorsahin/ChatGPT_Automation/commit/203a0a8e0108cd91ea0fb7141e7e5c756555265a)
