### ISSUE TITLE
Exception has occurred: WebDriverException (Windows 10)

### ISSUE THREAD

**Issue by dijikul** [ugorsahin/ChatGPT_Automation#3]
Following the quick example:

```
from handler import Handler

chatgpt = Handler(<<my username>>, <<my password>>)

answer = chatgpt.interact("Hello, how are you today")

print(answer)
```

I receive the following error:

```
Exception has occurred: WebDriverException
Message: unknown error: cannot connect to chrome at 127.0.0.1:65421
from unknown error: unable to discover open pages
Stacktrace:
Backtrace:
	GetHandleVerifier [0x007ADCE3+50899]
	(No symbol) [0x0073E111]
	(No symbol) [0x00645588]
	(No symbol) [0x006655A9]
	(No symbol) [0x0065F5B1]
	(No symbol) [0x0065F391]
	(No symbol) [0x00691FFE]
	(No symbol) [0x00691CEC]
	(No symbol) [0x0068B6F6]
	(No symbol) [0x00667708]
	(No symbol) [0x0066886D]
	GetHandleVerifier [0x00A13EAE+2566302]
	GetHandleVerifier [0x00A492B1+2784417]
	GetHandleVerifier [0x00A4327C+2759788]
	GetHandleVerifier [0x00845740+672048]
	(No symbol) [0x00748872]
	(No symbol) [0x007441C8]
	(No symbol) [0x007442AB]
	(No symbol) [0x007371B7]
	BaseThreadInitThunk [0x769F0099+25]
	RtlGetAppContainerNamedObjectPath [0x77AD7B6E+286]
	RtlGetAppContainerNamedObjectPath [0x77AD7B3E+238]
  File "C:\Users\<<user>>\Projects\ChatGPT_Selenium\handler.py", line 94, in __init__
    self.browser = uc.Chrome(options=options, use_subprocess=True)
  File "C:\Users\<<user>>\Projects\ChatGPT_Selenium\chat.py", line 8, in <module>
    chatgpt = Handler(YOUR_USERNAME, YOUR_PASSWORD)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:65421
from unknown error: unable to discover open pages
Stacktrace:
Backtrace:
	GetHandleVerifier [0x007ADCE3+50899]
	(No symbol) [0x0073E111]
	(No symbol) [0x00645588]
	(No symbol) [0x006655A9]
	(No symbol) [0x0065F5B1]
	(No symbol) [0x0065F391]
	(No symbol) [0x00691FFE]
	(No symbol) [0x00691CEC]
	(No symbol) [0x0068B6F6]
	(No symbol) [0x00667708]
	(No symbol) [0x0066886D]
	GetHandleVerifier [0x00A13EAE+2566302]
	GetHandleVerifier [0x00A492B1+2784417]
	GetHandleVerifier [0x00A4327C+2759788]
	GetHandleVerifier [0x00845740+672048]
	(No symbol) [0x00748872]
	(No symbol) [0x007441C8]
	(No symbol) [0x007442AB]
	(No symbol) [0x007371B7]
	BaseThreadInitThunk [0x769F0099+25]
	RtlGetAppContainerNamedObjectPath [0x77AD7B6E+286]
	RtlGetAppContainerNamedObjectPath [0x77AD7B3E+238]

```

I have confirmed both WebDriver and undetected_chromedriver function on their own with sample scripts, however the handler doesn't seem to want to connect.  
I've tried specifying the chromedriver.exe in the options within handler.py but that hasn't work, and specifying the path wasn't necessary in the quick checks of undetected_chromedriver and WebDriver on their own.

I'm using ChromeDriver 112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}) attempting to align with Chrome 112.0.5615.138 (Official Build) (64-bit).

Thanks in advance for any thoughts.

**Comment by ugorsahin** [comment]
This may be because of a mismatch between undetected_chrome and Chrome versions. Check this page: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/868 . 

You can try removing and reinstalling Selenium and undetected_chrome as a brute-force solution, but I'm not sure if that helps.

**But before doing that**, can you pass `headless=False` to the Handler, perhaps it is the headless mode that causes the problem.

**Comment by dijikul** [comment]
Thanks for that!

With `headless=False` it fails with `Raised Exceptions` enabled while debugging, but only because it's looking for that element that doesn't exist.  Disabling the checkbox allows it to run successfully in non-headless mode, with the exception handling set to Pass.

![image](https://user-images.githubusercontent.com/2670528/234744718-522e86e8-2232-4c12-a71d-615fcba92652.png)


Setting it back to headless however fails with a similar error, though not a version mismatch like the linked Issue: 

```
Exception has occurred: WebDriverException       (note: full exception trace is shown but execution is paused at: <module>)
Message: unknown error: cannot connect to chrome at 127.0.0.1:64823
from unknown error: unable to discover open pages
```


In headless mode while debugging it appears to hang on the line 94 of handler.py when trying to create the chatgpt instance:

```
...
        self.browser = uc.Chrome(options=options)
        self.browser.set_page_load_timeout(15)
...
```

After the 15 second timeout the element fails to attach because there's seemingly no browser instance accessible by Python.

I'm not sure how to troubleshoot this, but happy to do so if there's more information I can provide.  For now it's cool that I can play with it in non-headless mode, so thanks again for your quick reply!

**Comment by dijikul** [comment]
Might be related/caused by https://github.com/ugorsahin/ChatGPT_Selenium/issues/4

**Comment by ugorsahin** [comment]
I fixed the problem with new settings, please pull again and let me know if headless is functional on your end as well.

**Comment by dijikul** [comment]
Looks like it's hanging on the same issue, catching an Exception on line 32 of chatgpt_client.py:

```
Exception has occurred: WebDriverException
Message: unknown error: cannot connect to chrome at 127.0.0.1:49266
from unknown error: unable to discover open pages
```



As a note, to make the usage example work with the changes, I had to change the module reference like so: `from chatgpt_automation.chatgpt_client import ChatGPT_Client` and also update the `chatgpt = Handler(...` reference to `chatgpt = ChatGPT_Client(...`, but otherwise the changes looked clean.

**Comment by ugorsahin** [comment]
Can you upgrade the undetected chrome to the latest version? I guess that may be the reason.

**Comment by dijikul** [comment]
Can you link to how I go about doing that?  I've placed the updated EXE in the project folder but it seems the code is downloading the 112 version directly, though that should be the right one for my version of Chrome:

```
DEBUG:undetected_chromedriver.patcher:getting release number from /LATEST_RELEASE
DEBUG:undetected_chromedriver.patcher:downloading from https://chromedriver.storage.googleapis.com/112.0.5615.49/chromedriver_win32.zip
DEBUG:undetected_chromedriver.patcher:unzipping C:\Users\dijikul\AppData\Local\Temp\tmpyrwhuokd
INFO:undetected_chromedriver.patcher:patching driver executable C:\Users\dijikul\appdata\roaming\undetected_chromedriver\1dedd9a927d6d106_chromedriver.exe
```

Tagging these two issues which seem related:

1) https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1135

2) https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1046

**Comment by ugorsahin** [comment]
Oh, you can try pasting the following line to the command line (cmd or powershell)

`python -m pip install undetected-chromedriver==3.4.6`

**Comment by dijikul** [comment]
Thank you!

Upgrading undetected-chromedriver to 3.4.6 now allows it to run headlessly.

It looks like the 3.1.7 version might have been re-downloading due to the requirements.txt specification: https://github.com/ugorsahin/ChatGPT_Automation/blob/main/requirements.txt

Thanks again!  This repo is great!
