### ISSUE TITLE
[QUESTION] Why did you write the code this way?

### ISSUE THREAD

**Issue by MovieHolic-Plex** [ugorsahin/ChatGPT_Automation#31]
in chatgpt_client.py , line 262

        for each_line in question.split('\n'):
            text_area.send_keys(each_line)
            text_area.send_keys(Keys.SHIFT + Keys.ENTER)

Why did you split based on \n?
If you don't do this, will openAI detect an anomaly?

Can't I just insert it all at once instead of splitting it (by \n)?

**Comment by ugorsahin** [comment]
`Enter` is a special key with an assigned function: It sends the message. If you need a new line, you need to push shift+enter.
