### ISSUE TITLE
 [BUG] Error in pass_verification, the service not load...

### ISSUE THREAD

**Issue by isMMa** [ugorsahin/ChatGPT_Automation#34]
Traceback (most recent call last):
  File "code.py", line 18, in <module>
    chatgpt = ChatGPT_Client(OPENAI_EMAIL, OPENAI_PASSWORD)
  File "/usr/local/lib/python3.8/site-packages/chatgpt_automation/chatgpt_client.py", line 105, in __init__
    self.pass_verification()
  File "/usr/local/lib/python3.8/site-packages/chatgpt_automation/chatgpt_client.py", line 146, in pass_verification
    verify_button[0].click()
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=117.0.5938.92); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x56149368c6b3 <unknown>
#1 0x5614933621e7 <unknown>
#2 0x56149336ff09 <unknown>
#3 0x561493367644 <unknown>
#4 0x56149336625b <unknown>
#5 0x5614933689c0 <unknown>
#6 0x561493368a7c <unknown>
#7 0x5614933aae19 <unknown>
#8 0x56149339f451 <unknown>
#9 0x5614933cb0c2 <unknown>
#10 0x56149339ef16 <unknown>
#11 0x5614933cb28e <unknown>
#12 0x5614933e4322 <unknown>
#13 0x5614933cae93 <unknown>
#14 0x56149339d934 <unknown>
#15 0x56149339e71e <unknown>
#16 0x561493651cb8 <unknown>
#17 0x561493655bf0 <unknown>
#18 0x56149366019c <unknown>
#19 0x561493656808 <unknown>
#20 0x56149362327f <unknown>
#21 0x56149367ae88 <unknown>
#22 0x56149367b059 <unknown>
#23 0x56149368b843 <unknown>
#24 0x7ff5b955c044 <unknown>

**Comment by StolenGalaxy** [comment]
Was this a temporary issue or does it still happen?

**Comment by isMMa** [comment]
Now its still happen, not work since 1 day ago... and now its not working.

**Comment by StolenGalaxy** [comment]
Maybe try adding a catch:  `except Exceptions.StaleElementReferenceException: logging.info('Verification button went stale')` to pass_verification and see if it persists

**Comment by isMMa** [comment]
Client is trying to connect for 30 minutes and no progress in ChatGPT_Client(EMAIL,PASS)

I haven't been able to use it for 2 days. On different computers, with different accounts and in a Docker environment.

**Comment by isMMa** [comment]
Error: 

  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div id="challenge-stage" style="display: none;"></div> is not clickable at point (150, 32). Other element would receive the click: <div class="container">...</div>
  (Session info: chrome=117.0.5938.92)

**Comment by isMMa** [comment]
Using verbose:

2023/09/28 21:36:45 INFO Verbose mode active
2023/09/28 21:36:45 INFO Loading undetected Chrome
2023/09/28 21:36:46 INFO patching driver executable /root/.local/share/undetected_chromedriver/undetected_chromedriver
2023/09/28 21:36:46 INFO Loaded Undetected chrome
2023/09/28 21:36:46 INFO Opening chatgpt
2023/09/28 21:36:46 INFO ChatGPT is ready to interact
2023/09/28 21:36:46 INFO Unable to locate text area tag. Switching to ID search
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    answer = chatgpt.interact("Hello, how are you today")
  File "/usr/local/lib/python3.8/site-packages/chatgpt_automation/chatgpt_client.py", line 297, in interact
    raise RuntimeError('Unable to find the text prompt area. Please raise an issue with verbose=True')
RuntimeError: Unable to find the text prompt area. Please raise an issue with verbose=True

**Comment by isMMa** [comment]
Any idea? please need help!

**Comment by ugorsahin** [comment]
Yes, it seems Cloudflare won't let you pass the verification. It is probably IP-based detection. There is no easy solution for this problem and it is not related to the this repository.

**Comment by isMMa** [comment]
It is strange since the same thing happens to me with another IP and also if I log in with the browser it works perfectly.

**Comment by isMMa** [comment]
Ok, I'm done seeing the problem. It is not a cloudflare block. It is an incompatibility between the latest version of chrome and chrome undetected:

My last code:

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt install ./google-chrome-stable_current_amd64.deb -y

And my new code:

COPY chrome/chrome_114_amd64.deb /tmp/
RUN ls 
#Instalar
RUN apt install /tmp/chrome_114_amd64.deb -y

Now its works using chrome 114!!

**Comment by ugorsahin** [comment]
```
2023/09/28 21:46:10 INFO Clicked verification button
2023/09/28 21:46:11 INFO Clicked verification button
2023/09/28 21:46:12 INFO Clicked verification button
2023/09/28 21:46:13 INFO Clicked verification button
2023/09/28 21:46:15 INFO Clicked verification button
2023/09/28 21:46:16 INFO Clicked verification button
2023/09/28 21:46:17 INFO Clicked verification button
2023/09/28 21:46:18 INFO Clicked verification button
2023/09/28 21:46:19 INFO Clicked verification button
2023/09/28 21:46:20 INFO Clicked verification button
2023/09/28 21:46:21 INFO Clicked verification button
2023/09/28 21:46:22 INFO Clicked verification button
```

This input shows that the undetected-chrome has already hooked the client, although current version of undetected-chrome may not be compatible with the chrome-117. I'm happy that you solved the problem.
